### ISSUE TITLE
用晶晨宝盒更新固件后除/tmp外所有文件系统都是只读，无法保存配置，请问如何降级

### ISSUE THREAD

**Issue by rendaa** [breakings/OpenWrt#27]
如题。固件版本是6.1.57，N1盒子。

OpenWrt是在U盘上运行的。

可能因此问题造成一些配置文件不能保存，有关的服务如 SmartDNS 无法启动。
目前临时解决方式是shell里执行 mount / -o rw,remount 然后再保存那些配置后，相关服务可正确启动。
然而重启后又有若干配置没有保存、那些服务又不能启动。
因为域名不能正确解析，晶晨宝盒里检查更新等功能也总是出错。晶晨宝盒日志记录里有"Invalid OpenWrt download address."的错误。

望改进此问题、并希望考虑提供一回退至上一版内核的方法。

谢谢！

**Comment by breakings** [comment]
用宝盒的命令更新内核，指定内核版本就行

**Comment by rendaa** [comment]
感谢回复！回头我试试。
