### ISSUE TITLE
winscp帐户总是验证错误

### ISSUE THREAD

**Issue by 3136083906** [breakings/OpenWrt#7]
12月8日的固件是不是有问题？

**Comment by breakings** [comment]
> 12月8日的固件是不是有问题？

你用什么版本登录winscp 日志提示仁德

**Comment by 3136083906** [comment]
> > 12月8日的固件是不是有问题？
> 
> 你用什么版本winscp 日志提示什么 建议先核对密码输入 我这边没任何问题

好，我再试试

**Comment by 3136083906** [comment]
> > 12月8日的固件是不是有问题？
> 
> 你用什么版本winscp 日志提示什么 建议先核对密码输入 我这边没任何问题

又试了今天的版本，还是一样啊，f大的固件就没问题

**Comment by breakings** [comment]
> > > 12月8日的固件是不是有问题？
> > 
> > 
> > 你用什么版本winscp 日志提示什么 建议先核对密码输入 我这边没任何问题
> 
> 又试了今天的版本，还是一样啊，f大的固件就没问题

什么鬼哦 、你用的哪个releases tag的固件 armv8_mini是云编译的

**Comment by 3136083906** [comment]
> > > > 12月8日的固件是不是有问题？
> > > 
> > > 
> > > 你用什么版本winscp 日志提示什么 建议先核对密码输入 我这边没任何问题
> > 
> > 
> > 又试了今天的版本，还是一样啊，f大的固件就没问题
> 
> 什么鬼哦 、你用的哪个releases tag的固件 armv8_mini是云编译的

又发现一个问题啊，章鱼星球固件5.15内核，小核心一直是100hz最低频率运行
